#define OBJECTS_COUNT 32
#define OBJECT_SIZE sizeof(ObjectText)

#define ALLOC_SECTORS 255
#define SECTOR_SIZE 96

#define MALLOC_SIZE RES_EGA_S
#define TMP_BUFFER_SIZE 256

#define CODE_ADDRESS_SIZE 16